package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.forbidec.domain.AssertUtils.bigDecimalCompareTo;

public class BaremeMentionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeMentionAllPropertiesEquals(BaremeMention expected, BaremeMention actual) {
        assertBaremeMentionAutoGeneratedPropertiesEquals(expected, actual);
        assertBaremeMentionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeMentionAllUpdatablePropertiesEquals(BaremeMention expected, BaremeMention actual) {
        assertBaremeMentionUpdatableFieldsEquals(expected, actual);
        assertBaremeMentionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeMentionAutoGeneratedPropertiesEquals(BaremeMention expected, BaremeMention actual) {
        assertThat(actual)
            .as("Verify BaremeMention auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeMentionUpdatableFieldsEquals(BaremeMention expected, BaremeMention actual) {
        assertThat(actual)
            .as("Verify BaremeMention relevant properties")
            .satisfies(a -> assertThat(a.getLibelleLong()).as("check libelleLong").isEqualTo(expected.getLibelleLong()))
            .satisfies(a -> assertThat(a.getLibelleCourt()).as("check libelleCourt").isEqualTo(expected.getLibelleCourt()))
            .satisfies(a ->
                assertThat(a.getBorneMin()).as("check borneMin").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBorneMin())
            )
            .satisfies(a -> assertThat(a.getMinInclus()).as("check minInclus").isEqualTo(expected.getMinInclus()))
            .satisfies(a ->
                assertThat(a.getBorneMax()).as("check borneMax").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBorneMax())
            )
            .satisfies(a -> assertThat(a.getMaxInclus()).as("check maxInclus").isEqualTo(expected.getMaxInclus()))
            .satisfies(a -> assertThat(a.getOrdreAffichage()).as("check ordreAffichage").isEqualTo(expected.getOrdreAffichage()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeMentionUpdatableRelationshipsEquals(BaremeMention expected, BaremeMention actual) {
        assertThat(actual)
            .as("Verify BaremeMention relationships")
            .satisfies(a -> assertThat(a.getCentre()).as("check centre").isEqualTo(expected.getCentre()));
    }
}
