package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.forbidec.domain.AssertUtils.bigDecimalCompareTo;

public class CentreFormationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentreFormationAllPropertiesEquals(CentreFormation expected, CentreFormation actual) {
        assertCentreFormationAutoGeneratedPropertiesEquals(expected, actual);
        assertCentreFormationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentreFormationAllUpdatablePropertiesEquals(CentreFormation expected, CentreFormation actual) {
        assertCentreFormationUpdatableFieldsEquals(expected, actual);
        assertCentreFormationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentreFormationAutoGeneratedPropertiesEquals(CentreFormation expected, CentreFormation actual) {
        assertThat(actual)
            .as("Verify CentreFormation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentreFormationUpdatableFieldsEquals(CentreFormation expected, CentreFormation actual) {
        assertThat(actual)
            .as("Verify CentreFormation relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getVille()).as("check ville").isEqualTo(expected.getVille()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()))
            .satisfies(a -> assertThat(a.getEnteteDocument()).as("check enteteDocument").isEqualTo(expected.getEnteteDocument()))
            .satisfies(a -> assertThat(a.getSignataire()).as("check signataire").isEqualTo(expected.getSignataire()))
            .satisfies(a -> assertThat(a.getLogoUrl()).as("check logoUrl").isEqualTo(expected.getLogoUrl()))
            .satisfies(a -> assertThat(a.getNbCyclesCursus()).as("check nbCyclesCursus").isEqualTo(expected.getNbCyclesCursus()))
            .satisfies(a ->
                assertThat(a.getNoteMaximale())
                    .as("check noteMaximale")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getNoteMaximale())
            )
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentreFormationUpdatableRelationshipsEquals(CentreFormation expected, CentreFormation actual) {
        assertThat(actual)
            .as("Verify CentreFormation relationships")
            .satisfies(a -> assertThat(a.getPays()).as("check pays").isEqualTo(expected.getPays()));
    }
}
