package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.forbidec.domain.AssertUtils.bigDecimalCompareTo;

public class CoursAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursAllPropertiesEquals(Cours expected, Cours actual) {
        assertCoursAutoGeneratedPropertiesEquals(expected, actual);
        assertCoursAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursAllUpdatablePropertiesEquals(Cours expected, Cours actual) {
        assertCoursUpdatableFieldsEquals(expected, actual);
        assertCoursUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursAutoGeneratedPropertiesEquals(Cours expected, Cours actual) {
        assertThat(actual)
            .as("Verify Cours auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursUpdatableFieldsEquals(Cours expected, Cours actual) {
        assertThat(actual)
            .as("Verify Cours relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getLibelleLong()).as("check libelleLong").isEqualTo(expected.getLibelleLong()))
            .satisfies(a -> assertThat(a.getLibelleCourt()).as("check libelleCourt").isEqualTo(expected.getLibelleCourt()))
            .satisfies(a -> assertThat(a.getOrdreAffichage()).as("check ordreAffichage").isEqualTo(expected.getOrdreAffichage()))
            .satisfies(a -> assertThat(a.getNbPeriodes()).as("check nbPeriodes").isEqualTo(expected.getNbPeriodes()))
            .satisfies(a ->
                assertThat(a.getCoefficient())
                    .as("check coefficient")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCoefficient())
            )
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursUpdatableRelationshipsEquals(Cours expected, Cours actual) {
        // empty method
    }
}
