package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CycleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleAllPropertiesEquals(Cycle expected, Cycle actual) {
        assertCycleAutoGeneratedPropertiesEquals(expected, actual);
        assertCycleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleAllUpdatablePropertiesEquals(Cycle expected, Cycle actual) {
        assertCycleUpdatableFieldsEquals(expected, actual);
        assertCycleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleAutoGeneratedPropertiesEquals(Cycle expected, Cycle actual) {
        assertThat(actual)
            .as("Verify Cycle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleUpdatableFieldsEquals(Cycle expected, Cycle actual) {
        assertThat(actual)
            .as("Verify Cycle relevant properties")
            .satisfies(a -> assertThat(a.getAnnee()).as("check annee").isEqualTo(expected.getAnnee()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getCloture()).as("check cloture").isEqualTo(expected.getCloture()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCycleUpdatableRelationshipsEquals(Cycle expected, Cycle actual) {
        assertThat(actual)
            .as("Verify Cycle relationships")
            .satisfies(a -> assertThat(a.getCentre()).as("check centre").isEqualTo(expected.getCentre()));
    }
}
