package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnseignantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnseignantAllPropertiesEquals(Enseignant expected, Enseignant actual) {
        assertEnseignantAutoGeneratedPropertiesEquals(expected, actual);
        assertEnseignantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnseignantAllUpdatablePropertiesEquals(Enseignant expected, Enseignant actual) {
        assertEnseignantUpdatableFieldsEquals(expected, actual);
        assertEnseignantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnseignantAutoGeneratedPropertiesEquals(Enseignant expected, Enseignant actual) {
        assertThat(actual)
            .as("Verify Enseignant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnseignantUpdatableFieldsEquals(Enseignant expected, Enseignant actual) {
        assertThat(actual)
            .as("Verify Enseignant relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPrenom()).as("check prenom").isEqualTo(expected.getPrenom()))
            .satisfies(a -> assertThat(a.getLibelleLong()).as("check libelleLong").isEqualTo(expected.getLibelleLong()))
            .satisfies(a -> assertThat(a.getLibelleCourt()).as("check libelleCourt").isEqualTo(expected.getLibelleCourt()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()))
            .satisfies(a -> assertThat(a.getKeycloakUserId()).as("check keycloakUserId").isEqualTo(expected.getKeycloakUserId()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnseignantUpdatableRelationshipsEquals(Enseignant expected, Enseignant actual) {
        // empty method
    }
}
