package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtudiantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtudiantAllPropertiesEquals(Etudiant expected, Etudiant actual) {
        assertEtudiantAutoGeneratedPropertiesEquals(expected, actual);
        assertEtudiantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtudiantAllUpdatablePropertiesEquals(Etudiant expected, Etudiant actual) {
        assertEtudiantUpdatableFieldsEquals(expected, actual);
        assertEtudiantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtudiantAutoGeneratedPropertiesEquals(Etudiant expected, Etudiant actual) {
        assertThat(actual)
            .as("Verify Etudiant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtudiantUpdatableFieldsEquals(Etudiant expected, Etudiant actual) {
        assertThat(actual)
            .as("Verify Etudiant relevant properties")
            .satisfies(a -> assertThat(a.getMatricule()).as("check matricule").isEqualTo(expected.getMatricule()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPrenom()).as("check prenom").isEqualTo(expected.getPrenom()))
            .satisfies(a -> assertThat(a.getParticularite()).as("check particularite").isEqualTo(expected.getParticularite()))
            .satisfies(a -> assertThat(a.getDateNaissance()).as("check dateNaissance").isEqualTo(expected.getDateNaissance()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()))
            .satisfies(a -> assertThat(a.getAnneeEntree()).as("check anneeEntree").isEqualTo(expected.getAnneeEntree()))
            .satisfies(a -> assertThat(a.getCursusAcheve()).as("check cursusAcheve").isEqualTo(expected.getCursusAcheve()))
            .satisfies(a -> assertThat(a.getAnneeFinale()).as("check anneeFinale").isEqualTo(expected.getAnneeFinale()))
            .satisfies(a -> assertThat(a.getKeycloakUserId()).as("check keycloakUserId").isEqualTo(expected.getKeycloakUserId()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtudiantUpdatableRelationshipsEquals(Etudiant expected, Etudiant actual) {
        assertThat(actual)
            .as("Verify Etudiant relationships")
            .satisfies(a -> assertThat(a.getPays()).as("check pays").isEqualTo(expected.getPays()));
    }
}
