package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.forbidec.domain.AssertUtils.bigDecimalCompareTo;

public class EvaluationRealiseeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationRealiseeAllPropertiesEquals(EvaluationRealisee expected, EvaluationRealisee actual) {
        assertEvaluationRealiseeAutoGeneratedPropertiesEquals(expected, actual);
        assertEvaluationRealiseeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationRealiseeAllUpdatablePropertiesEquals(EvaluationRealisee expected, EvaluationRealisee actual) {
        assertEvaluationRealiseeUpdatableFieldsEquals(expected, actual);
        assertEvaluationRealiseeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationRealiseeAutoGeneratedPropertiesEquals(EvaluationRealisee expected, EvaluationRealisee actual) {
        assertThat(actual)
            .as("Verify EvaluationRealisee auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationRealiseeUpdatableFieldsEquals(EvaluationRealisee expected, EvaluationRealisee actual) {
        assertThat(actual)
            .as("Verify EvaluationRealisee relevant properties")
            .satisfies(a -> assertThat(a.getNote()).as("check note").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getCompteDansMoyenne()).as("check compteDansMoyenne").isEqualTo(expected.getCompteDansMoyenne()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getCommentaire1()).as("check commentaire1").isEqualTo(expected.getCommentaire1()))
            .satisfies(a -> assertThat(a.getCommentaire2()).as("check commentaire2").isEqualTo(expected.getCommentaire2()))
            .satisfies(a -> assertThat(a.getCommentaire3()).as("check commentaire3").isEqualTo(expected.getCommentaire3()))
            .satisfies(a -> assertThat(a.getSaisiePar()).as("check saisiePar").isEqualTo(expected.getSaisiePar()))
            .satisfies(a -> assertThat(a.getSaisieLe()).as("check saisieLe").isEqualTo(expected.getSaisieLe()))
            .satisfies(a -> assertThat(a.getValideePar()).as("check valideePar").isEqualTo(expected.getValideePar()))
            .satisfies(a -> assertThat(a.getValideeLe()).as("check valideeLe").isEqualTo(expected.getValideeLe()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationRealiseeUpdatableRelationshipsEquals(EvaluationRealisee expected, EvaluationRealisee actual) {
        assertThat(actual)
            .as("Verify EvaluationRealisee relationships")
            .satisfies(a -> assertThat(a.getEvaluationPrevue()).as("check evaluationPrevue").isEqualTo(expected.getEvaluationPrevue()))
            .satisfies(a -> assertThat(a.getEtudiant()).as("check etudiant").isEqualTo(expected.getEtudiant()));
    }
}
