package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.forbidec.domain.AssertUtils.bigDecimalCompareTo;

public class EvaluationPrevueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationPrevueAllPropertiesEquals(EvaluationPrevue expected, EvaluationPrevue actual) {
        assertEvaluationPrevueAutoGeneratedPropertiesEquals(expected, actual);
        assertEvaluationPrevueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationPrevueAllUpdatablePropertiesEquals(EvaluationPrevue expected, EvaluationPrevue actual) {
        assertEvaluationPrevueUpdatableFieldsEquals(expected, actual);
        assertEvaluationPrevueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationPrevueAutoGeneratedPropertiesEquals(EvaluationPrevue expected, EvaluationPrevue actual) {
        assertThat(actual)
            .as("Verify EvaluationPrevue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationPrevueUpdatableFieldsEquals(EvaluationPrevue expected, EvaluationPrevue actual) {
        assertThat(actual)
            .as("Verify EvaluationPrevue relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getLibelleImpression()).as("check libelleImpression").isEqualTo(expected.getLibelleImpression()))
            .satisfies(a ->
                assertThat(a.getCoefficient())
                    .as("check coefficient")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCoefficient())
            )
            .satisfies(a -> assertThat(a.getCompteDansMoyenne()).as("check compteDansMoyenne").isEqualTo(expected.getCompteDansMoyenne()))
            .satisfies(a ->
                assertThat(a.getNoteMaximale())
                    .as("check noteMaximale")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getNoteMaximale())
            )
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationPrevueUpdatableRelationshipsEquals(EvaluationPrevue expected, EvaluationPrevue actual) {
        assertThat(actual)
            .as("Verify EvaluationPrevue relationships")
            .satisfies(a -> assertThat(a.getCycle()).as("check cycle").isEqualTo(expected.getCycle()))
            .satisfies(a -> assertThat(a.getEnseignant()).as("check enseignant").isEqualTo(expected.getEnseignant()))
            .satisfies(a -> assertThat(a.getMatiere()).as("check matiere").isEqualTo(expected.getMatiere()))
            .satisfies(a -> assertThat(a.getSousMatiere()).as("check sousMatiere").isEqualTo(expected.getSousMatiere()))
            .satisfies(a -> assertThat(a.getCours()).as("check cours").isEqualTo(expected.getCours()))
            .satisfies(a -> assertThat(a.getTypeTache()).as("check typeTache").isEqualTo(expected.getTypeTache()));
    }
}
