package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EvenementEtudiantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvenementEtudiantAllPropertiesEquals(EvenementEtudiant expected, EvenementEtudiant actual) {
        assertEvenementEtudiantAutoGeneratedPropertiesEquals(expected, actual);
        assertEvenementEtudiantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvenementEtudiantAllUpdatablePropertiesEquals(EvenementEtudiant expected, EvenementEtudiant actual) {
        assertEvenementEtudiantUpdatableFieldsEquals(expected, actual);
        assertEvenementEtudiantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvenementEtudiantAutoGeneratedPropertiesEquals(EvenementEtudiant expected, EvenementEtudiant actual) {
        assertThat(actual)
            .as("Verify EvenementEtudiant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvenementEtudiantUpdatableFieldsEquals(EvenementEtudiant expected, EvenementEtudiant actual) {
        assertThat(actual)
            .as("Verify EvenementEtudiant relevant properties")
            .satisfies(a -> assertThat(a.getDateEvenement()).as("check dateEvenement").isEqualTo(expected.getDateEvenement()))
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvenementEtudiantUpdatableRelationshipsEquals(EvenementEtudiant expected, EvenementEtudiant actual) {
        assertThat(actual)
            .as("Verify EvenementEtudiant relationships")
            .satisfies(a -> assertThat(a.getEtudiant()).as("check etudiant").isEqualTo(expected.getEtudiant()));
    }
}
