package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HabilitationCycleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabilitationCycleAllPropertiesEquals(HabilitationCycle expected, HabilitationCycle actual) {
        assertHabilitationCycleAutoGeneratedPropertiesEquals(expected, actual);
        assertHabilitationCycleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabilitationCycleAllUpdatablePropertiesEquals(HabilitationCycle expected, HabilitationCycle actual) {
        assertHabilitationCycleUpdatableFieldsEquals(expected, actual);
        assertHabilitationCycleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabilitationCycleAutoGeneratedPropertiesEquals(HabilitationCycle expected, HabilitationCycle actual) {
        assertThat(actual)
            .as("Verify HabilitationCycle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabilitationCycleUpdatableFieldsEquals(HabilitationCycle expected, HabilitationCycle actual) {
        assertThat(actual)
            .as("Verify HabilitationCycle relevant properties")
            .satisfies(a -> assertThat(a.getKeycloakUserId()).as("check keycloakUserId").isEqualTo(expected.getKeycloakUserId()))
            .satisfies(a -> assertThat(a.getRoleFonctionnel()).as("check roleFonctionnel").isEqualTo(expected.getRoleFonctionnel()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabilitationCycleUpdatableRelationshipsEquals(HabilitationCycle expected, HabilitationCycle actual) {
        assertThat(actual)
            .as("Verify HabilitationCycle relationships")
            .satisfies(a -> assertThat(a.getCentre()).as("check centre").isEqualTo(expected.getCentre()))
            .satisfies(a -> assertThat(a.getCycle()).as("check cycle").isEqualTo(expected.getCycle()));
    }
}
