package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.forbidec.domain.AssertUtils.bigDecimalCompareTo;

public class HistoriqueNoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueNoteAllPropertiesEquals(HistoriqueNote expected, HistoriqueNote actual) {
        assertHistoriqueNoteAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueNoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueNoteAllUpdatablePropertiesEquals(HistoriqueNote expected, HistoriqueNote actual) {
        assertHistoriqueNoteUpdatableFieldsEquals(expected, actual);
        assertHistoriqueNoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueNoteAutoGeneratedPropertiesEquals(HistoriqueNote expected, HistoriqueNote actual) {
        assertThat(actual)
            .as("Verify HistoriqueNote auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueNoteUpdatableFieldsEquals(HistoriqueNote expected, HistoriqueNote actual) {
        assertThat(actual)
            .as("Verify HistoriqueNote relevant properties")
            .satisfies(a ->
                assertThat(a.getNoteAvant()).as("check noteAvant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getNoteAvant())
            )
            .satisfies(a ->
                assertThat(a.getNoteApres()).as("check noteApres").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getNoteApres())
            )
            .satisfies(a -> assertThat(a.getStatutAvant()).as("check statutAvant").isEqualTo(expected.getStatutAvant()))
            .satisfies(a -> assertThat(a.getStatutApres()).as("check statutApres").isEqualTo(expected.getStatutApres()))
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getModifiePar()).as("check modifiePar").isEqualTo(expected.getModifiePar()))
            .satisfies(a -> assertThat(a.getModifieLe()).as("check modifieLe").isEqualTo(expected.getModifieLe()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueNoteUpdatableRelationshipsEquals(HistoriqueNote expected, HistoriqueNote actual) {
        assertThat(actual)
            .as("Verify HistoriqueNote relationships")
            .satisfies(a -> assertThat(a.getEvaluationRealisee()).as("check evaluationRealisee").isEqualTo(expected.getEvaluationRealisee())
            );
    }
}
