package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InscriptionCycleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionCycleAllPropertiesEquals(InscriptionCycle expected, InscriptionCycle actual) {
        assertInscriptionCycleAutoGeneratedPropertiesEquals(expected, actual);
        assertInscriptionCycleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionCycleAllUpdatablePropertiesEquals(InscriptionCycle expected, InscriptionCycle actual) {
        assertInscriptionCycleUpdatableFieldsEquals(expected, actual);
        assertInscriptionCycleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionCycleAutoGeneratedPropertiesEquals(InscriptionCycle expected, InscriptionCycle actual) {
        assertThat(actual)
            .as("Verify InscriptionCycle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionCycleUpdatableFieldsEquals(InscriptionCycle expected, InscriptionCycle actual) {
        assertThat(actual)
            .as("Verify InscriptionCycle relevant properties")
            .satisfies(a -> assertThat(a.getDateInscription()).as("check dateInscription").isEqualTo(expected.getDateInscription()))
            .satisfies(a -> assertThat(a.getCycleTermine()).as("check cycleTermine").isEqualTo(expected.getCycleTermine()))
            .satisfies(a -> assertThat(a.getGroupe()).as("check groupe").isEqualTo(expected.getGroupe()))
            .satisfies(a -> assertThat(a.getCommentaire1()).as("check commentaire1").isEqualTo(expected.getCommentaire1()))
            .satisfies(a -> assertThat(a.getCommentaire2()).as("check commentaire2").isEqualTo(expected.getCommentaire2()))
            .satisfies(a -> assertThat(a.getCommentaire3()).as("check commentaire3").isEqualTo(expected.getCommentaire3()))
            .satisfies(a -> assertThat(a.getCommentaire5()).as("check commentaire5").isEqualTo(expected.getCommentaire5()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionCycleUpdatableRelationshipsEquals(InscriptionCycle expected, InscriptionCycle actual) {
        assertThat(actual)
            .as("Verify InscriptionCycle relationships")
            .satisfies(a -> assertThat(a.getCycle()).as("check cycle").isEqualTo(expected.getCycle()))
            .satisfies(a -> assertThat(a.getEtudiant()).as("check etudiant").isEqualTo(expected.getEtudiant()));
    }
}
