package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MatiereAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAllPropertiesEquals(Matiere expected, Matiere actual) {
        assertMatiereAutoGeneratedPropertiesEquals(expected, actual);
        assertMatiereAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAllUpdatablePropertiesEquals(Matiere expected, Matiere actual) {
        assertMatiereUpdatableFieldsEquals(expected, actual);
        assertMatiereUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAutoGeneratedPropertiesEquals(Matiere expected, Matiere actual) {
        assertThat(actual)
            .as("Verify Matiere auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereUpdatableFieldsEquals(Matiere expected, Matiere actual) {
        assertThat(actual)
            .as("Verify Matiere relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getLibelleLong()).as("check libelleLong").isEqualTo(expected.getLibelleLong()))
            .satisfies(a -> assertThat(a.getLibelleCourt()).as("check libelleCourt").isEqualTo(expected.getLibelleCourt()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereUpdatableRelationshipsEquals(Matiere expected, Matiere actual) {
        // empty method
    }
}
