package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParametreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreAllPropertiesEquals(Parametre expected, Parametre actual) {
        assertParametreAutoGeneratedPropertiesEquals(expected, actual);
        assertParametreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreAllUpdatablePropertiesEquals(Parametre expected, Parametre actual) {
        assertParametreUpdatableFieldsEquals(expected, actual);
        assertParametreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreAutoGeneratedPropertiesEquals(Parametre expected, Parametre actual) {
        assertThat(actual)
            .as("Verify Parametre auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreUpdatableFieldsEquals(Parametre expected, Parametre actual) {
        assertThat(actual)
            .as("Verify Parametre relevant properties")
            .satisfies(a -> assertThat(a.getCle()).as("check cle").isEqualTo(expected.getCle()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getValeur()).as("check valeur").isEqualTo(expected.getValeur()))
            .satisfies(a -> assertThat(a.getTypeValeur()).as("check typeValeur").isEqualTo(expected.getTypeValeur()))
            .satisfies(a -> assertThat(a.getModifiableUi()).as("check modifiableUi").isEqualTo(expected.getModifiableUi()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreUpdatableRelationshipsEquals(Parametre expected, Parametre actual) {
        assertThat(actual)
            .as("Verify Parametre relationships")
            .satisfies(a -> assertThat(a.getCentre()).as("check centre").isEqualTo(expected.getCentre()));
    }
}
