package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SousMatiereAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousMatiereAllPropertiesEquals(SousMatiere expected, SousMatiere actual) {
        assertSousMatiereAutoGeneratedPropertiesEquals(expected, actual);
        assertSousMatiereAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousMatiereAllUpdatablePropertiesEquals(SousMatiere expected, SousMatiere actual) {
        assertSousMatiereUpdatableFieldsEquals(expected, actual);
        assertSousMatiereUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousMatiereAutoGeneratedPropertiesEquals(SousMatiere expected, SousMatiere actual) {
        assertThat(actual)
            .as("Verify SousMatiere auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousMatiereUpdatableFieldsEquals(SousMatiere expected, SousMatiere actual) {
        assertThat(actual)
            .as("Verify SousMatiere relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getLibelleLong()).as("check libelleLong").isEqualTo(expected.getLibelleLong()))
            .satisfies(a -> assertThat(a.getLibelleCourt()).as("check libelleCourt").isEqualTo(expected.getLibelleCourt()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousMatiereUpdatableRelationshipsEquals(SousMatiere expected, SousMatiere actual) {
        // empty method
    }
}
