package org.forbidec.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeTacheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTacheAllPropertiesEquals(TypeTache expected, TypeTache actual) {
        assertTypeTacheAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeTacheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTacheAllUpdatablePropertiesEquals(TypeTache expected, TypeTache actual) {
        assertTypeTacheUpdatableFieldsEquals(expected, actual);
        assertTypeTacheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTacheAutoGeneratedPropertiesEquals(TypeTache expected, TypeTache actual) {
        assertThat(actual)
            .as("Verify TypeTache auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTacheUpdatableFieldsEquals(TypeTache expected, TypeTache actual) {
        assertThat(actual)
            .as("Verify TypeTache relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getLibelleLong()).as("check libelleLong").isEqualTo(expected.getLibelleLong()))
            .satisfies(a -> assertThat(a.getLibelleCourt()).as("check libelleCourt").isEqualTo(expected.getLibelleCourt()))
            .satisfies(a -> assertThat(a.getEntreDansMoyenne()).as("check entreDansMoyenne").isEqualTo(expected.getEntreDansMoyenne()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTacheUpdatableRelationshipsEquals(TypeTache expected, TypeTache actual) {
        // empty method
    }
}
